### ISSUE TITLE
Feature Request for Visible Search Bar

### ISSUE THREAD

**Issue by wolfsiren** [cdevroe/unmark#104]
Want to start off by saying I love Unmark! It is very helpful. While using it though I found that the search bar is in the menu system and because I use search a lot to find things I would like to put in a feature request to have the search bar visible at all times instead of in the menu system.

**Comment by cdevroe** [comment]
@wolfsiren Thanks for the kind words. This is an excellent suggestion.

**Comment by cdevroe** [comment]
@wolfsiren The search is not available at the top of the UI at all times in 2020.1. Enjoy!!
