### ISSUE TITLE
Forced to archive a mark to delete it...

### ISSUE THREAD

**Issue by nothing-fr** [cdevroe/unmark#111]
Please, change this behavior.

It don't think it's necessary to archive the mark before deleting it, we should be able to do it directly from the edit pane.

**Comment by cdevroe** [comment]
@nothing-fr We made this choice very much on purpose. Some of our very early builds of Unmark didn't even have a way to delete a mark but we eventually settled on giving people _some_ way of doing so. 

If you'd like to create a way to do this please feel free to modify your local version as we do not think we'll make this change across the entire application.

What does everyone else think?

**Comment by jwbargsten** [comment]
In terms of workflow, doesn't matter if it is email, selecting holiday destinations or saving stuff in your brain, it basically works the same (also GTD, getting things done, is based on this). You have a inbox, document with candidates or short term memory. Back to unmark: after initial "mark as interesting" (which you do by adding the link to unmark), you revise and throw out. This is the approach of 90% of all humans. You would not put everything from you short term memory into long term memory to forget it afterwards. Not intuitive. Also mails you will not sort into archive to delete them afterwards. Also not intuitive. I see managing bookmarks similar. On the second look you discover stuff you don't need anymore, so there should be a possibility to throw it out.

**Comment by cdevroe** [comment]
@jwbargsten Thanks for the feedback.

**Comment by virtadpt** [comment]
I'd like to second making links easier to delete.  One of my use cases for Unmark is temporarily storing links to stuff that I write articles about, and when the article's done (and the links are referenced from the article) being able to delete the links from Unmark will keep things neat and tidy (especially when using Unmark as a personal bookmark manager in addition to keeping track of links to write about).  Both the "archive a link" and the "re-bookmark but hit the delete button instead" workflows are not intuitive, and tend to cause more problems than they solve.

**Comment by cdevroe** [comment]
This will be included in 1.9
