### ISSUE TITLE
Extend Unmark's importer to support new services

### ISSUE THREAD

**Issue by cdevroe** [cdevroe/unmark#112]
Currently supported: Browser exports from Safari, Chrome, Firefox. Also Pinboard and Delicious.

What else would you like to see?
- [ ] Shaarli (taken from comment on #45 )
- [x] Pocket
- [ ] Instapaper
- [ ] Wallabag

What else?

**Comment by nothing-fr** [comment]
https://www.wallabag.org/ ? it's like Pocket & Instapaper but with Self-Hosted version...

**Comment by cdevroe** [comment]
@nothing-fr updated.

**Comment by w00kie** [comment]
kippt.com (exports to a "Netscape bookmarks html format")

**Comment by cdevroe** [comment]
@w00kie Excellent! That means Unmark already supports importing it.

**Comment by JoshHrach** [comment]
Add a vote to Instapaper for me.

**Comment by ckrack** [comment]
Out of personal need i created importers as a custom extension to unmark.
https://github.com/ckrack/unmark/tree/custom-import

I will not create a pull request, as these already seem to be in the private code and the ones i created are tweaked as in creating tags for the bookmark folders of netscape import.
Also the code is not the cleanest, as i tried to use the Mark_Import class without changing it, and it's depending on checks like the one for export_version, that are dependent on the JSON Importer and are not needed for other imports..

**Comment by cdevroe** [comment]
Cool @ckrack

**Comment by ckrack** [comment]
This is how i'd be going about it:
- Create an ``interface`` that all importers use. Basically the ``importFile`` and ``validateUpload`` methods.
- Make the counting and result returning simpler
- uncouple the dependencies in ``Mark_Import``
- add a config option that contains the importers, which is then cycled over in the controller. 
``$importers = ['delicious', 'json', 'pocket'];``
that way others can be added easily..

But then again, you might have all this already?

**Comment by virtadpt** [comment]
del.icio.us, which only allows export to HTML.

**Comment by virtadpt** [comment]
@ckrack you are a sir among beings - I just used your branch to import several thousand bookmarks from del.icio.us after a weekend of hacking to write a Netscape bookmarks-to-Unmark JSON document converter.  Your code just saved my sanity - PLEASE file a pull request!

**Comment by cdevroe** [comment]
@ckrack I'm going to look through your extension... as I didn't in the past and see what we can pull from it.

**Comment by cdevroe** [comment]
In #168 both Delicious and Pinboard now can be imported using their HTML format.

**Comment by smth** [comment]
So I should already be seeing an option to import from browser? I have 1.7.1.2 installed, and only see "Unmark file" and "Readability file".

**Comment by cdevroe** [comment]
@smth Upgrade to 1.7.2 (if you haven't already using the branch) a little later today for this feature.
