### ISSUE TITLE
Submit login via enter key after autofill.

### ISSUE THREAD

**Issue by michaeloboyle** [cdevroe/unmark#118]
If browser auto-fills credentials, a click on the form is still required to set focus so for can be submitted with enter key. If focus were set on load, then login could happen with one step.

**Comment by williamknauss** [comment]
@michaeloboyle 
This should be easily accomplished by just setting the focus on the username field when the page loads correct?

**Comment by cdevroe** [comment]
@williamknauss Yeah. We can do this with a minimal bit of JS.

**Comment by cdevroe** [comment]
I'll have to clean up Milestone 1.6.3 since the person that was working on that build has abandoned development on Unmark. But this should still make the cut for an upcoming release.
