### ISSUE TITLE
Use as server for Mozilla Reading List

### ISSUE THREAD

**Issue by jsit** [cdevroe/unmark#122]
Mozilla has a reading list server that can be used with Firefox 38+:

https://github.com/mozilla-services/readinglist

It would be incredible if Unmark could be set up to be used as a custom reading list server (available in Firefox's about:config under readinglist.server).

**Comment by cdevroe** [comment]
Any other Firefox users want this? If so, please chime in on how to make this happen.

**Comment by cdevroe** [comment]
@jsit Have you done any investigating on how to pull this off?

**Comment by cdevroe** [comment]
Perhaps a better approach to this would be "importing" from Mozilla's Reading List service moreso than trying to make Unmark work within Firefox.

**Comment by jsit** [comment]
Wouldn't you then have to import every time you added a new item to Reading
List? Besides which, Firefox doesn't have a native reading list; it only
works with external/hosted services. So you'd have to use some other
reading list, like Pocket, then export, then import to Unmark. Every time
you added new content.

**Comment by cdevroe** [comment]
I see, @jsit... my understanding of Reading list was incorrect.

Because our list of things to do is a mile long right now, I don't see myself getting to this very quickly. But it'd be great if you wanted to poke around and try.

**Comment by r0bbie** [comment]
Completely understand this being low priority at the moment, but just wanted to +1 that I'd love to see this feature. :)
