### ISSUE TITLE
notes not saving

### ISSUE THREAD

**Issue by ghidra** [cdevroe/unmark#136]
When writing a note when making a bookmark, if I do not change the label after, the note will not save. For example, marking a youtube video, unmark automatically applies "watch" label. Leaving a not, and saving will not save the note. So to make it save the note, I must change the "watch" to something else then back to "watch".

This is specifically happening on my install of unmark on my personal server.

Which by the way, unmark is awesome! There are a few other small things that I would like to bring up or try to fix myself given the time. Thank you.

**Comment by cdevroe** [comment]
@ghidra Thank you for reporting this. Can you open your browser's Console and see if the request to save the note is being sent and rejected? This is done asynchronously.

**Comment by ghidra** [comment]
Hi sorry, I havent forgotten this. I just havent saved any links in 3 days... And since I havent figured out to delete marks yet, I'm waiting till I have a link to save, and I will report back!

**Comment by cdevroe** [comment]
@ghidra To delete a mark, archive it first, then go into the archive and delete it from there.

**Comment by ghidra** [comment]
Thanks for taking the time to look at this.
I just tried to save a new mark that was a random site, that gave me unlabeled, wrote a quick note, with the console open... but of course, it closed as soon as i hit submit.
As well, it did NOT save my note as expected.
Sorry for the very noob question, how would you suggest watching the console and having it not close on submit... not use the bookmarklet?

**Comment by cdevroe** [comment]
@ghidra Notes save on blur so you do not need to click "submit". Alternatively you can edit notes from the main interface.

I haven't seen this issue reported by anyone else and I haven't experienced it myself. Please see if you can confirm the issue and send us the error.

**Comment by cdevroe** [comment]
@ghidra Still having this issue? If so, could you try #157?

**Comment by cdevroe** [comment]
@ghidra We just pushed 1.7.1 would you mind trying it? https://github.com/plainmade/unmark/releases/tag/v1.7.1
