### ISSUE TITLE
CSS broken on Firefox 49.0.1

### ISSUE THREAD

**Issue by ghost** [cdevroe/unmark#167]
The Unmark layout overflows in both width and height in Firefox 49.0.1.
I'm not sure if this issue is present in other versions.

**Comment by cdevroe** [comment]
@sooprdogg We'll look into this, thanks for reporting it.

**Comment by sooprdogg** [comment]
@cdevroe Of course! So sorry to keep you waiting. This is specifically on Windows.
![capture](https://cloud.githubusercontent.com/assets/20822849/18975563/a24cb400-8670-11e6-9f1b-23d063b1c5e2.PNG)
![capture2](https://cloud.githubusercontent.com/assets/20822849/18975565/a455f45a-8670-11e6-9f01-2bc656be3d74.PNG)

**Comment by cdevroe** [comment]
This has been addressed 1.8.0
