### ISSUE TITLE
Upgrade app to latest CodeIgniter

### ISSUE THREAD

**Issue by cdevroe** [cdevroe/unmark#179]
Unmark is currently on 2.x it'd be great to go to 3.x

**Comment by iamonuwa** [comment]
Converted Unmark to 3.x

**Comment by cdevroe** [comment]
@iamonuwa Did you submit a PR? That'd be fantastic.

**Comment by iamonuwa** [comment]
Am submitting a PR now

**Comment by iamonuwa** [comment]
@cdevroe why use the Plain_ subclass prefix? The app is fully functional with Codeigniter version 3.x system/core files

**Comment by cdevroe** [comment]
@iamonuwa The Plain_ prefix is because that is our company name.
