### ISSUE TITLE
Feature request: Looser interpretation of tags.

### ISSUE THREAD

**Issue by bryce-admin** [cdevroe/unmark#182]
I've noticed that using freeform tags ("This is #sometag, this is #anothertag, and this is me embedding a #tag at the end.") has a subtle problem.  The problem occurs when the user clicks on a tag with some punctuation immediately following it (e.g., "#sometag") Unmark returns the "The URI you submitted has disallowed characters" error.

Would it be feasible to loosen interpretation of tags to ignore commas, semicolons, colons, and suchlike?  That would make it easier to use tags in a freeform manner (embedded in notes and text).

**Comment by cdevroe** [comment]
@bryce-admin I like where this is going. However, in the 1.8.x line of Unmark we'll be introducing a dedicated "tags" input area that will work much more like a traditional tag input like you see elsewhere. So this issue you're having will go away.

**Comment by bryce-admin** [comment]
Will there be a migration path for this feature (i.e., would #tags in existing bookmarks be copied into it), or would it be an "every bookmarks following that upgrade will have it" sort of thing?

**Comment by cdevroe** [comment]
@bryce-admin All tags are already stored in a tag index... they are not only managed via that text area. So yes, they will all come along for the ride.

**Comment by cdevroe** [comment]
I'm going to close this as tags will be getting proper treatment in an upcoming release.
