### ISSUE TITLE
Import del.icio.us bookmarks correctly

### ISSUE THREAD

**Issue by gyger** [cdevroe/unmark#185]
I tried to import the delicious bookmarks, the tags are all stored as one hashtag if the words are not separated by a tag+comma + space+tag, but only by tag+comma+tag.

The structure looks like
```
<DT><A HREF="http://koel.phanan.net/" ADD_DATE="1462304847" PRIVATE="0"  TAGS="music,server,stream,personal">koel</A>
<DD>Personal music streaming server
```

Additionally the <DD> line is ignored.

A good solution would be to add the DD to the text comment of the imported entry and add the hashtags in the line below.

**Comment by cdevroe** [comment]
@gyger Would you mind trying this again in 1.7.2?

**Comment by gyger** [comment]
Unfortunately not, I have left the product.

Colin Devroe <notifications@github.com> schrieb am Mo., 28. Jan. 2019,
22:29:
