### ISSUE TITLE
marking bookmarks as public

### ISSUE THREAD

**Issue by jamesacampbell** [cdevroe/unmark#186]
I want the ability to make a set of bookmarks I tag a specific tag or tags as public so I can access them / use a script to grab them without having to be redirected to my login screen. If this is already implemented apologies.

**Comment by cdevroe** [comment]
@jamesacampbell We've been asked about this sort of feature in the past. Sort of like "collections" that could be shared ala Readability or other services.

At this time we do not plan to add any "public" facing piece to Unmark. We prefer to keep all user data (and their content) private and siloed. 

Sorry to burst your bubble here and thanks for giving Unmark a try.

**Comment by jamesacampbell** [comment]
Totally understand. Thanks
