### ISSUE TITLE
Bookmarklet sometimes stores new entries without descriptions.

### ISSUE THREAD

**Issue by virtadpt** [cdevroe/unmark#187]
From time to time (out of ten or fifteen usages every day, two or three of them) the bookmarklet creates a new link in a self-hosted Unmark instance which does not have any notes if they were entered initially.  This happens when already logged into my Unmark instance or not (the new window asks me to log in first).  This happens on Firefox v49 (64-bit) on Linux and Chrome 54.0.2840.98 (64-bit) on Mac OSX (10.11.6).  I haven't figured out yet how to make this happen on demand.

Unmark version 1.7.1 is installed at this time.

**Comment by cdevroe** [comment]
@virtadpt The notes feature is sent asynchronously to Unmark. If at all possible, could you capture your Console and the HTTP Request that fails when this happens?

**Comment by virtadpt** [comment]
I'll give it a try the next time it happens.

**Comment by cdevroe** [comment]
@virtadpt Still an issue?

**Comment by virtadpt** [comment]
Yup. Happens about 50% of the time on both Chrome and Firefox.

**Comment by cdevroe** [comment]
So you put in notes and they don't save? We'll have to try to fix this. I have never experienced it but perhaps there is an issue. Maybe you can make a screencast video?

**Comment by virtadpt** [comment]
That's about the size of it.

I can take a crack at it tomorrow evening, I'm booked for an all-nighter at work tonight and might not have the compute cycles to try to record it.

**Comment by cdevroe** [comment]
@virtadpt Does this happen for you in 1.8.0? If so, that screencast and perhaps information from your browser console would be helpful.

**Comment by virtadpt** [comment]
It did, but I've migrated off of Unmark so I don't have it handy anymore.  Sorry.
