### ISSUE TITLE
/setup No database connection settings were found in the database config file.

### ISSUE THREAD

**Issue by adri66** [cdevroe/unmark#192]
Hello, I'm try to install unmark but can I run setup, the page return 

> An Error Was Encountered
> 
> No database connection settings were found in the database config file.

After edit line 42 on system/database/DB.php `include($file_path);` to `include $file_path;`
It's work fine

**Comment by adri66** [comment]
And for install the correct url is /install/setup and no /setup

**Comment by cdevroe** [comment]
@adri66 I have never seen this issue... also, the file you edited is a system file within CodeIgniter so my guess is that your issue is only on your environment.

(If I'm wrong on this, please someone let me know.)
