### ISSUE TITLE
Session bug with PHP 7.1

### ISSUE THREAD

**Issue by weaktyper** [cdevroe/unmark#193]
I couldn't login due to a 403 error on PHP_FPM 7.1

The issue is related to cookie sessions. 

More can be read here:

- https://github.com/bcit-ci/CodeIgniter/issues/4830

Changing to PHP_FPM 7.0 fixes the issue.

**Comment by weaktyper** [comment]
There are other bugs with  PHP_FPM 7.0
 PHP_FPM 5.6 --> this is the latest version i could get up and running.

**Comment by ysragh** [comment]
I'm also on 7.0 and have no issues with PHP itself, but with MySQL. Probably that's your problem too.
php -v gives me:

    [yzzi@ysragh.com htdocs]$ php-fpm7.0 -v
    PHP 7.0.13-0ubuntu0.16.04.1 (fpm-fcgi)
    Copyright (c) 1997-2016 The PHP Group
    Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
        with Zend OPcache v7.0.13-0ubuntu0.16.04.1, Copyright (c) 1999-2016, by Zend Technologies

I could not log in unil I altered the SQL-Mode like this:

    mysql > SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));

That's a ugly workaround, but until this gets sorted by the upstream maintainers, it just works.

Semms they are a bit late on catching on with all the issues and merge requests. Let's hope for the best :)

**Comment by cshort** [comment]
@ysragh I had the same MySQL issue, but there's still an issue with it and PHP 7.  I haven't had the time to investigate, but since upgrading all I see is a blank page and I'm not getting anything in error logs.

Prior to the fix you mentioned I was getting a 500 error.

**Comment by ysragh** [comment]
Weird, good thing I'm still on 7.0 and haven't upgraded to 7.1 yet. Hopefully the maintainers keep up with the issues and merge requests :)

Have you tried downgrading to PHP 7.0, @cshort ?

**Comment by mazedlx** [comment]
Same problem here, CI 3.1.3 has problems with sessions when using PHP 7.0 and PHP 7.1. Switched PHP-FPM back to 5.6, everything works fine.

Using NGINX 1.4.6 on Ubuntu.

**Comment by cdevroe** [comment]
@mazedlx @cshort @ysragh @weaktyper Once we get to 1.8 released we'll work on updating Code Igniter to the latest version which should support the latest version of PHP.

**Comment by cshort** [comment]
@emkae been awhile, but the server I have it on is only 7.0 and not 7.1

**Comment by cdevroe** [comment]
@walialu I _believe_ the mySQL issue with sql_mode should be fixed in anything after 1.7.1.4. Could you see if that is true?

**Comment by mpiric** [comment]
Check below link. It works fine. I had older CodeIgniter version and PHP version 7.1.2 and I faced the same issue.

Just download CodeIgniter 3 and replace "system" folder of the older version with the latest version and its work.

https://stackoverflow.com/questions/45756370/codeigniter-session-is-not-working-on-php-7/45756437#45756437

**Comment by walialu** [comment]
It's gone!
