### ISSUE TITLE
Less than intuitive UI/UX for opening, editing, deleting, and archiving links.

### ISSUE THREAD

**Issue by virtadpt** [cdevroe/unmark#197]
The workflow for editing a link is a little pixel-twitchy, and could probably use some improvement.  Here's how it stands right now:

- Open Unmark.
- Click on a link underneath the title but not on the "open this link" arrow button or the "archive this link" checkmark button.
- Try again a few times because it might open the saved link a few times.  This is especially prevalent on mobile devices.
- The link opens in the right-hand panel.  Click the "Notes (click to edit)" bar.
- Edit the link.
- Click the "Editing mark info" bar to save the edits.

The UI is also a little misleading in a couple of places.  Here is a possible workflow that remediates some of the shortcomings.

- Open Unmark.
- Click an "Edit link" button on the link's entry.  This opens the link editor in the right-hand column.
- Edit the link's entry.
- Click a "Save link" button above the link editor in the right-hand column.

It might also be helpful to change the "open this link" diagonal arrow to "open link", and the "archive this link" checkmark button to read "archive", or something to that effect that's a bit more intuitive.

It may also be helpful to add a "delete this link" button to each link (perhaps in the right-hand column, where the link editor usually appears) because not everybody wants to archive links permanently, and the workflow of "open the link, change to the link's tab, use the ''add to Unmark'' bookmarklet to delete the link, close the tab" is kind of clunky.

**Comment by weaktyper** [comment]
unmark is a great open source application but I would agree, without your help I would not have figured out how to edit the links. I also believe that `delete link` would be useful.

**Comment by cdevroe** [comment]
@virtadpt @weaktyper Have you tried version 1.8.0? Try that branch and let me know what you think of our new way of editing links.

**Comment by virtadpt** [comment]
I have not.  Let me figure out how to install it on my current instance...

**Comment by cdevroe** [comment]
Let's keep this discussion going but please around the 1.8 design. @virtadpt Have you given it a try?

**Comment by virtadpt** [comment]
Not yet.  I updated to 1.7.1.3 two days ago (just after its release).  I'm at work so I can't update to 1.7.2 because I can't SSH out.

**Comment by cdevroe** [comment]
@virtadpt @weaktyper Please give 1.8.0 pre-release a try. Also more code updates to that coming today.

**Comment by cdevroe** [comment]
@virtadpt @weaktyper This has been signifigantly improved in 2020.1 - you no longer need to archive a link in order to delete it, you can edit the title, tags, and notes, very easily, etc. I hope you love it!
