### ISSUE TITLE
[Feature Request] Enhance usability surrounding tags

### ISSUE THREAD

**Issue by weaktyper** [cdevroe/unmark#198]
I am enjoying the unmark application and ecosystem. Here are some suggestions that I believe could make it even better.

- Tags on display in badges under every link. (in the middle column)
- Auto-suggest as starting to type tags - when adding or editing a link. This will be especially useful to avoid adding two tags with almost the same name. Eg. `#prototype` and `#prototypes`.
- Allow to delete tags completely with some thought about how to handle orphaned links.
- Allow to change the spelling of a tag.
- Allow browse tags in more UI friendly manner - perhaps some drag n' drop feature or Show a drop-down searchable list of tags on the 3rd (right hand column) under the edit a bookmark section. (There is a lot of white pace there).

**Comment by chepec** [comment]
Agree completely with @weaktyper on points 1 and 2:

> - Tags on display in badges under every link. (in the middle column)
> - Auto-suggest as starting to type tags - when adding or editing a link. This will be especially useful to avoid adding two tags with almost the same name. Eg. #prototype and #prototypes.

And something along a tag cloud (bullet point 5 above) would be awesome.

I just installed and tested unmark (coming from self-hosted lobsters), and I like unmark much better so far, but miss the overview of all tags.

**Comment by cdevroe** [comment]
@weaktyper 1.8.0 release is out. Please take a look as some of the things you talked about may have been addressed. Not all of them have been, however, and a few of them I'm going to promote to being their own "tickets" soon enough.

**Comment by cdevroe** [comment]
@weaktyper Auto-suggest is now in 2020.1 release which was rolled into master today. The rest of the items on the list will likely not happen for a long time as "tag clouds" are a low priority for our use and our customers. However, if you would like to have something like this please feel free to commit a PR!
