### ISSUE TITLE
Unable to Login - 1.7.1.2

### ISSUE THREAD

**Issue by ct2000** [cdevroe/unmark#203]
I seem to unable to login after setup - user is created but I get white tick and loop back to login screen.  logs do not indicate an error.  - on version  1.7.1.2

**Comment by zsuiram** [comment]
Same here. Tried with PHP 5.6/7.0/7.1 - no luck.

**Comment by petrk94** [comment]
I just installed it on my VPS hoster Uberspace and dont have a problem, can you show what you mean?

**Comment by cdevroe** [comment]
@ct2000 @zsuiram I've seen many stumble into this because they didn't run migrations. But as @petrk94 Can you give us more information? Perhaps looking in your logs?

**Comment by cdevroe** [comment]
@ct2000 Please try the latest release.

**Comment by WinndyBoy** [comment]
I have the same problem with the lastest release. After setup and register complete I login with new email and password, rotating animation appears and fails to log me in. Any help or clues where to look ?

I'm running on arch, with latest versions of mysql, or mariadb... can't see any error messages

**Comment by CliffHan** [comment]
I've met same problem on 1.7.2

**Comment by tim6300243** [comment]
I have the same problem with ver 1.7.2
I login with registered email and password,screen disappears and then returns to login screen.

Initial setup seems to be successful.
There was a registered email in the mysql table(users).

PC environment is as follows.
OS :Windows10
PHP:PHP7.1.12
DB :MySQL Server 5.7
Web:Nginx1.13.8

I write nginx.conf using the contents of the wiki "Nginx Configuration"

nginx access log is follow
192.168.xx.xx - - [08/Jan/2018:13:08:40 +0900] "GET /json/auth/error HTTP/2.0" 403 30 "https://unmark.xxxx.xxx.jp/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"

There was not anything like a bug in the application logs
($config['log_threshold'] = 2;)

**Comment by tim6300243** [comment]
I can login PHP 5.6.30
I use it with PHP 5.6 until ver 1.8

Maybe this is the cause
https://github.com/cdevroe/unmark/issues/193

**Comment by Tuncay-Ayhan** [comment]
@tim6300243 Bingo! That was it for me!
