### ISSUE TITLE
Installing unmark in a sub directory

### ISSUE THREAD

**Issue by jflatz** [cdevroe/unmark#204]
I'm attempting to install Unmark in example.com/GitHub/unmark however /setup is 404 and assests are being directed to example.com/assets/ instead of example.com/GitHub/unmark/assets/

**Comment by cdevroe** [comment]
@jflatz I have never tried to install Unmark in a sub-directory. If you do a search in the issues you'll see many have done so successfully. So please look through those issues to find some things you can try.
