### ISSUE TITLE
VPS, unmark booklet and Chrome Extension

### ISSUE THREAD

**Issue by petrk94** [cdevroe/unmark#205]
Hello,
I have a little problem with the usage configuration.
Im running successful the unmark installation on my VPS at Uberspace. And when I try to open the unmark booklet, than I get the IP adress of the Shared server and cant use it.
The other question is the Chrome Extension. I dont have seen yet an option how to connect the Chrome Extension with the own installation.

See Screenshot:
![unmark](https://cloud.githubusercontent.com/assets/19719052/24569900/c0aeb4f6-1668-11e7-8830-7af3199ff60d.PNG)

**Comment by chepec** [comment]
Regarding your second question (pointing the Chrome extension to your self-hosted instance), [see this guide](https://computers.tutsplus.com/tutorials/host-your-own-bookmarking-webapp-with-unmark--cms-21385). I'll include parts of the text below just in case the page disappears (but the guide is nicer, also has descriptive screenshots).

First, download the extension files from its GitHub repository, by clicking the Download ZIP button to the right. Unzip the file to a location you can easily locate on your hard drive. Navigate into the `unmark-chrome-master` folder and open the file called `manifest.json` in a text editor. Find this bit of code in the file:

```
"permissions": [
"tabs",
"contextMenus",
"*://unmark.it/"
 ],
```

Now, change the domain `unmark.it` to point to the subdomain you created for your Unmark install, so the block of code in my file looks like this:

```
"permissions": [
"tabs",
"contextMenus",
"*://unmark.mydomain.com/"
 ],
```

When you're done, save the file in the same location.

Next, open `js/unmark/base.js` in a text editor. We'll need to replace the URL in the second line, which looks like this:

```
unmark.host = 'https://unmark.it';
```

Paste in your subdomain URL so the second line looks like this:

```
unmark.host =  'https://unmark.mydomain.com';
```

Launch Google Chrome, click the hamburger icon button, and select Tools > Extensions. Check the box at the top to enable Developer mode, and then click **Load unpacked extension**.

**Comment by cdevroe** [comment]
@chepec Thanks for answering this question. 🍺
