### ISSUE TITLE
Hand over project or grant another dev access?

### ISSUE THREAD

**Issue by walialu** [cdevroe/unmark#208]
Could you think of handing over this project or granting one or two devs access, so they can accept merge requests and fix bugs? Seems like you're pretty busy and the development seems to have stalled somehow, which is okay to me, but I really like this project and I really want this to succeed.

So what are you thinking about granting one or two other devs access, or handing it completely over?

**Comment by m1guelpf** [comment]
I would like to offer me for mantaining this project :smile:

**Comment by cdevroe** [comment]
@ysragh @m1guelpf I am going to be picking up this project again in earnest within a week or so. And I'd love more help to clean up many things! 

I somehow need to figure out a way to select some people to help. We can likely start using PRs. I'll be going through those within the next two days.

Really appreciate the help.

Also, unmark.it is down and will be coming back online shortly as well and we'll be launching 2.0 soon thereafter. The future of Unmark is bright! ✨

**Comment by m1guelpf** [comment]
@cdevroe Would be cool to have a roadmap, so people know what they can help at...

**Comment by cdevroe** [comment]
@m1guelpf We will work on one and likely put them in milestones. Likely starting with 1.9 as 1.8 is fairly close to completion.

**Comment by cdevroe** [comment]
Attn: I've now taken ownership of this project. I'll be working on it in earnest starting today. Watch for falling rocks for a week or so while I clean everything up. Any help is appreciated ... I'll be making a list of what I need soon.

@ysragh @m1guelpf

**Comment by m1guelpf** [comment]
Cool, please ping me when it's done so I can help!

**Comment by ysragh** [comment]
Count me (also) in, when it comes to helping, @cdevroe .

/cc @m1guelpf

**Comment by cdevroe** [comment]
@walialu @m1guelpf Would you two be willing to have a Skype conversation to discuss our Roadmap and collaboration? If so, please email me at colin [at] cdevroe.com and we can set up a time. Thanks!

**Comment by CodingFrieda** [comment]
[unmark.it](https://unmark.it/) directly sends me to this [GitHub repo](https://github.com/cdevroe/unmark). 

I discovered unmark today and am wondering if that is right or if [unmark.it](https://unmark.it/) was some sort of demo (like [wallabag.it](https://www.wallabag.it/) e.g.)? Does anyone have an unmark instance or a little GIF how unmark looks like? Is there an official [Docker](https://hub.docker.com/explore/) container or is [this one](https://hub.docker.com/r/pschmitt/unmark/) fine?

**Comment by walialu** [comment]
@codingfrieda, the docker image seems okay to me. It just pulls from plainmade/unmark which should automatically get redirected to cdevroe/unmark, because it has been legitimately handed over/transferred.

I'm on mobile right now and heading straight to bed, but can supply a little gif tomorrow, If you're still interested.

**Comment by walialu** [comment]
@CodingFrieda Here you have it: https://www.youtube.com/watch?v=AIP--sqlmpA

**Comment by CodingFrieda** [comment]
Thanks for your efforts, @walialu! 😘

**Comment by cdevroe** [comment]
@walialu Still willing to dive in and help? There's been a dozen releases since this thread, have you been using Unmark still?

2020.3 is being worked on currently and in milestones.
