### ISSUE TITLE
ROADMAP for May 2017

### ISSUE THREAD

**Issue by cdevroe** [cdevroe/unmark#209]
Hello all,

Thanks for your patience. I started a new job and have been working really hard there for months getting all new processes, team, and business model set up.

I now would like to start spending quality time bringing Unmark back from relative dead (though, thousands use the free hosted service). 

Roadmap for May 2017
- Release #173 (scope locked, just want to fix any bugs and get out the door)
- Release the redesign that is in 1.8.0 (there isn't much left to do here, so I will want to finish this quickly and get it into your hands)
- Release 1.8.1 (scope TBD but likely Code Igniter updates, reliability issues, and bug fixes)

Please see the Milestones for dates that I expect to have these finished.

Also @m1guelpf @ysragh have volunteered to help get this back off the ground. If anyone else would like to help out you can now see what our priorities are. Any questions can be asked here in this thread or you can give me your email address for Slack access: http://unmark.slack.com

**Comment by m1guelpf** [comment]
@cdevroe Thank you!
Could you please drop me an invite for Slack at the email in my GitHub profile?
Thank you!

**Comment by cdevroe** [comment]
Hello all,

It looks like we're going to run a bit behind on launching 1.8. It will likely be this weekend when we switch hosts.

**Comment by cdevroe** [comment]
Best laid plans.

1.7.2 is now out the door and we're very happy about that. All relevant updates will trickle into the 1.8 branch today. We're going to work hard to get that prepared for launch as we use it day-to-day and love it.
