### ISSUE TITLE
How To Install Unmark In SubDirectory ie. mydomain.com/subdir/

### ISSUE THREAD

**Issue by GaneshKandu** [cdevroe/unmark#211]
Hi

Getting 404 Error For all Javascript and css files when i access url on My Browser, working in Root
but i want to install in sub directory **ie**. _mydomain.com/subdir/_

**Comment by cdevroe** [comment]
TENTATIVE 

I would like this functionality as well. And we may work on this in 1.8.1

**Comment by GaneshKandu** [comment]
@cdevroe sorry but not working in sub-directory

**Comment by cdevroe** [comment]
We've decided to just wholesale not support this use case. So I'm closing the Issue.
