### ISSUE TITLE
Error 1055 after install

### ISSUE THREAD

**Issue by GotExx** [cdevroe/unmark#215]
Hi,
After entering the fields email and password I receive a error 1055.
`
A Database Error Occurred

Error Number: 1055

Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'umarks.user_marks_to_tags.user_marks_to_tag_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

SELECT user_marks_to_tags.tag_id, COUNT(user_marks_to_tags.tag_id) as total, tags.name, tags.slug FROM `user_marks_to_tags` INNER JOIN `users_to_marks` ON users_to_marks.users_to_mark_id = user_marks_to_tags.users_to_mark_id AND users_to_marks.archived_on IS NULL AND users_to_marks.active = '1' LEFT JOIN `tags` ON user_marks_to_tags.tag_id = tags.tag_id WHERE user_marks_to_tags.user_id = '1' GROUP BY user_marks_to_tags.tag_id ORDER BY user_marks_to_tags.user_marks_to_tag_id DESC LIMIT 10

Filename: /var/www/vhosts/domain.com/bookmarks/core/Plain_Model.php

Line Number: 71`

**Comment by cdevroe** [comment]
@GotExx We were able to fix this in version 1.7.1.4. Please pull that release and try again. Thank you.

**Comment by mx4k** [comment]
I receive the same error with version 1.7.2.
