### ISSUE TITLE
UI suggestion - More prominence for search / tags

### ISSUE THREAD

**Issue by smth** [cdevroe/unmark#216]
I think the priorities are a little off, when it comes screen space. As a small first step, I suggest that the search / tags panel is visible when either the "All marks" or "Archive" tabs are active. This will give easier access to these tools, as well as making the navigation more consistent. To compensate for this, the right most column could be removed from the default view; it doesn't really contain anything of use on a daily basis. (I'm referring to medium - large screens here)

**Comment by cdevroe** [comment]
@smth Have you reviewed ? https://github.com/cdevroe/unmark/tree/proposals/version-1.8

**Comment by smth** [comment]
No. Are there changes in this respect?
