### ISSUE TITLE
Screenshot?

### ISSUE THREAD

**Issue by sogen** [cdevroe/unmark#218]
Are there any screenshots of this app?

**Comment by cdevroe** [comment]
@sogen Here is what 1.7.x looks like:

<img width="1400" alt="screenshot 2017-09-21 10 27 51" src="https://user-images.githubusercontent.com/19237/30701178-9dc77950-9eb7-11e7-815c-035a97b54044.png">

And here is what 1.8.x will look like:

<img width="1403" alt="screenshot 2017-09-21 10 28 20" src="https://user-images.githubusercontent.com/19237/30701198-a9a521fa-9eb7-11e7-8601-cd658417d53c.png">
