### ISSUE TITLE
Database Error 1067

### ISSUE THREAD

**Issue by davidtessier** [cdevroe/unmark#221]
I am trying to install Unmark for the first time. 
When I try to run the setup I get the following error:
```
A DATABASE ERROR OCCURRED
Error Number: 1067
Invalid default value for 'datearchived'
ALTER TABLE `users_marks` ADD `datearchived` timestamp NOT NULL
Filename: /var/www/unmark/migrations/002_archive_stats.php
Line Number: 14
```
My system is running the following
```
Apache/2.4.18 (Ubuntu)
Database client version: libmysql - mysqlnd 5.0.12
PHP version: 7.0.28
Ubuntu 16.04
```
I have changed ownership of the unmark root folder to www-data.
I've created the database and database user account as instructed. 

Any idea why I get this error?

**Comment by cdevroe** [comment]
@davidtessier Looks like a migration issue. Until someone has the time to update the migrations, try this SQL file and skip the migrations step. 
[unmark_2018.sql.zip](https://github.com/cdevroe/unmark/files/2128601/unmark_2018.sql.zip)

**Comment by cdevroe** [comment]
@davidtessier I took some time today to figure out this issue. Line 14 of Migration 002 needs to be `$this->dbforge->add_column('users_marks', array('datearchived timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'));`

(By now, months later, you've likely solved this yourself or moved on. I'm simply adding for posterity. Also, this will be included in the next patch.)
