### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by sigmap** [cdevroe/unmark#224]
might be related to php 7.2

**Comment by mx4k** [comment]
Can confirm the same issue with PHP Version 7.1.22.

**Comment by cdevroe** [comment]
@sigmap Can you let me know what you've already tried? An error message perhaps? Have you run /install? Have you upgraded via /upgrade?

**Comment by sigmap** [comment]
Things broke after switching to php 7.2
Worked fine on php 5.6
