### ISSUE TITLE
Manually add a URL in Unmark UI

### ISSUE THREAD

**Issue by pcrockett** [cdevroe/unmark#242]
The version of Android I'm using on my tablet doesn't seem to handle the "Chrome in Android" bookmarking option as suggested [here](https://www.notion.so/Unmark-Help-How-to-add-bookmarks-cd5893f118ed40cd8400275e49f40d51). And the bookmarklet works, if you do it right. It's all very unintuitive though.

However web browsing in general works fine. It would be _so_ much easier if in the web UI, I could just paste a URL into a text box and click an "Add" button, and have it bookmarked right then and there.

**Comment by cdevroe** [comment]
@pcrockett Would you mind sharing your Android tablet, OS version, etc? I'm curious on what version of Android a PWA cannot be installed. Thanks in advance.

Version 1.9, which we pushed to [unmark.it](https://unmark.it) last week, will include the option to paste a URL into a form and add the bookmark to your list. This particular request duplicates #28 so I'll close this one after you reply to the above question. We expect to build the release for 1.9 today or tomorrow as we haven't found any show-stopping bugs in this release.

Thanks for writing in an issue!

**Comment by pcrockett** [comment]
Awesome, glad to hear it's already there!

To clarify, the PWA works in general, but when I go to share a URL, the app doesn't show up in my list of sharing options. Perhaps that would be the real root of the issue. The request to add a text box in the UI is just a workaround for users who for some reason can't use the share functionality.

It's a Lenovo TB-X304F ("Lenovo Tab") running Android 8.1.0.

**Comment by cdevroe** [comment]
@pcrockett Sorry for the silly question, but you have installed the app to your homescreen via Chrome, right?

**Comment by pcrockett** [comment]
Yes, I specifically tried adding to the home screen in Chrome. Using self-hosted Unmark version 1.8.1.

I also confirmed I don't have a "share" option on my Nexus 5X (Android 8.1.0).



Am 27. März 2019 20:15:29 MEZ schrieb Colin Devroe <notifications@github.com>:

**Comment by cdevroe** [comment]
@pcrockett Ok. Two things may be at work here. First, in order to install an app it must be HTTPS so if you aren't hosting your own copy via SSL you may not be able to take advantage of the PWA. This is true for all PWAs by the way not just Unmark.

Secondly, the "add bookmark" button is only available in 1.9.x but not in 1.8.1

**Comment by pcrockett** [comment]
HTTPS is definitely working. I do look forward to upgrading to 1.9 - Perhaps that'll fix the sharing issue as well. Thanks for your help.


Am 27. März 2019 20:55:37 MEZ schrieb Colin Devroe <notifications@github.com>:

**Comment by cdevroe** [comment]
@pcrockett Is your hosted Unmark at a public URL? If so, feel free to email me directly that URL and I can test it on the Pixel. It may just be Android 8? (I'm on 9)

**Comment by cdevroe** [comment]
I'm going to close this issue since it has been addressed in 1.9+. @pcrockett and I will continue this conversation via email.
