### ISSUE TITLE
Chrome Extension

### ISSUE THREAD

**Issue by runam0K** [cdevroe/unmark#251]
Is there an Update planned for the chrome extension?

I have updated my unmark installation to 1.9.1 and the crome extension does not work anymore.
I only see a small white box when I click on it. Chrome reports there is an error when I look in the extension menu.

![image](https://user-images.githubusercontent.com/3284319/56351880-580e4c00-61ce-11e9-8425-540f187a19f4.png)

**Comment by runam0K** [comment]
In the unmark webinterface I get this warning: 

`Deprecated: mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in ....system/database/drivers/mysql/mysql_driver.php on line 135`

When I add ini_set('display_errors','off'); to my database.php, then the chrome extension works again.

**Comment by cdevroe** [comment]
@runam0K Thanks for reporting this issue. You may have been bitten by a change in the requirements in Unmark going from one version to another. Please check the version of mySQL you have running against the version of Unmark's requirements in the Readme. 

If you still have the issue, we will look into why. I haven't personally seen this error.

The Chrome Extension is due for an overhaul once we ship 2.0 this month. In 2.0 we're adding a more traditional tagging model and UI so we'll need to add that to the Chrome Extension, update the design to match Unmark, and fix another issues.

**Comment by runam0K** [comment]
Thank you for your feedback. My mysql version is 5.1.73. I can change to mariadb 10.3.14 soon.

**Comment by hkockerbeck** [comment]
While MySQL 5.1.x probably _is_ too old for the current version of Unmark, there seems to be a different problem at play additionally. I just migrated my old Unmark installation to a new server and upgraded to 1.9.2. After the upgrade, I couldn't even log in. The error log said something to the effect of

    (...) PHP Deprecated:  mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in (...)
    (...) PHP Warning:  Cannot modify header information - headers already sent by (output started at (...)) in  (...)
    (...) PHP Warning:  session_start(): Cannot send session cookie - headers already sent by (output started at (...)) in  (...)
    (...) PHP Warning:  session_start(): Cannot send session cache limiter - headers already sent (output started at (...)) in  (...)

As far as I can tell, PHP kindly tells you that the old MySQL interface, with `mysql_pconnect()`, will soon be removed (as it has been in PHP 7.x). That output, though, throws Unmarks session management off. 

Changing the `dbdriver` in `application/config/database.php` to `mysqli` solved that issue:

    $db['default']['dbdriver'] = 'mysqli';
