### ISSUE TITLE
New version missing .js files?

### ISSUE THREAD

**Issue by MingyJ** [cdevroe/unmark#253]
I'm not sure if I have something incorrectly configured but on the newest release multiple .js files are return 404 and two of the .scss files are being requested as .css by the app, so again more 404's. 

I grabbed the last version 1.9.1 I believe, dropped it in leaving all else the same and I have a completely functional Unmark instance now. Anyone else experience this same issue?

**Comment by janstieler** [comment]
To fix it partial put a dot before every `/assets` so that it looks like `./assets/…`
But this can't fix the missing js files like
- unmark.loggedout.js

Cheers

**Comment by cdevroe** [comment]
@MingyJ Sorry that you had this issue and equally sorry it has taken me this long to log back into Github to help with these issues. Please see if you have the same issue in 1.9.2. Be sure you're downloading the binary file that has all of the JS / CSS compiled. If you are downloading the source, you'll need to build these files yourself using the instructions in the Readme. Perhaps you knew all of this.

**Comment by cdevroe** [comment]
@janstieler the issue you are reporting sounds like you are downloading the source and not the binary. To get the binary go to this URL https://github.com/cdevroe/unmark/releases/latest and click to download Unmark.zip

**Comment by cdevroe** [comment]
As a result of this thread, I'm going to add more simple instructions at the top of the Readme to download the latest compiled unmark.zip file. Sorry for any confusion!

**Comment by cdevroe** [comment]
Closing this, as the Readme in 2.0 is vastly improved and should be released soon.
