### ISSUE TITLE
Which grunt packages are necessary?

### ISSUE THREAD

**Issue by janstieler** [cdevroe/unmark#255]
Hi,
which npm modules for grunt are necessary to generate the needed css and js files?
I ask because normally I don't use grunt.

Cheers

**Comment by cdevroe** [comment]
@janstieler There is a package.json with all of the dependencies. Running `npm install` should result in you having everything that you need to build Unmark. If you run across issues, let me know and I'll do my best to debug those for you.

**Comment by cdevroe** [comment]
@janstieler Also, the latest build of version 2.0 (to be merged in soon) has updated the dependencies to the latest.
