### ISSUE TITLE
Marks being added to the Label table in the Database. 

### ISSUE THREAD

**Issue by vdisp** [cdevroe/unmark#260]
I added the `Add to Unmark` Link from the Profile Section as a Bookmark in my Browser and can add marks just fine this way.

However, I cannot figure out how to add/edit Labels from within the admin area. I figured I would try to add some manually via the Database and found that all my marks had also been added to the Label Table. I deleted all of them and added a couple Labels via the Insert function in phpMyAdmin and updated the Auto Increment count as well. I was able to reorder them manually but I can't seem to figure out how to change the color either, they are just gray.

Anyway, after changing the Marks on some of the entries to the new Labels, every Mark that I moved was also listed in the Label Table.

The order column has a note that says something about dragging to reorder, but I can seem to get anything like that to work.

**Comment by cdevroe** [comment]
@vdisp Can you supply a dataset?  A SQL file or something? Even screenshots of each table would help me to see what exactly is happening.

**Comment by vdisp** [comment]
Here are three screen shots: Main Table and Labels, and Marks.
[Unmark.zip](https://github.com/cdevroe/unmark/files/4665226/Unmark.zip)

![Annotation 2020-05-21 190014](https://user-images.githubusercontent.com/942975/82614576-2ec0ac00-9b96-11ea-8021-18ec73e20e9c.png)

![Annotation 2020-05-21 190015](https://user-images.githubusercontent.com/942975/82614582-31bb9c80-9b96-11ea-9cb6-31bd4be9418d.png)

![Annotation 2020-05-21 190016](https://user-images.githubusercontent.com/942975/82614589-341df680-9b96-11ea-8193-a2862a28b7c4.png)

**Comment by cdevroe** [comment]
@vdisp This all looks fine. The last table there is an index of the label with the URL. Looks good.
