### ISSUE TITLE
Friendly url in unmark 2020.1

### ISSUE THREAD

**Issue by GaneshKandu** [cdevroe/unmark#261]
Hi,

I am getting 404 error while installing unmark 2020.1 

getting 404 error while pointing at ```your-local-url/setup``` for install [https://github.com/cdevroe/unmark#from-zip](https://github.com/cdevroe/unmark#from-zip)

unmark downloaded from  [unmark.zip](https://github.com/cdevroe/unmark/releases/download/v2020.1/unmark.zip) link mentioned in [Version 2020.1](https://github.com/cdevroe/unmark/releases/tag/v2020.1) release

**Comment by cdevroe** [comment]
@GaneshKandu What URL are you using locally? localhost? 127.0.0.1?

**Comment by hkockerbeck** [comment]
The `.htaccess` seems to be missing from that archive.

**Comment by cdevroe** [comment]
@hkockerbeck That would do it! Thanks for letting us know!  @GaneshKandu You can [grab the .htaccess file](https://raw.githubusercontent.com/cdevroe/unmark/master/.htaccess) from the repo. We will add this to the next release to fix.

**Comment by GaneshKandu** [comment]
Hi @cdevroe 

Version is still 2020.1 in latest package.
