### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by gebeer** [cdevroe/unmark#262]
If you clone latest relaese 2.0.0 and try to do `npm install`, no node_modules folder is created. I spent an hour to solve this.
If you do `npm list` it complains about invalid version number "2.0"
This warning causes npm to not install any modules without throwing an error or any hint.

To resolve this, I changed the version number in package.json to "2.0.0"

Now `npm install` runs smoothly :-)

**Comment by cdevroe** [comment]
@gebeer I cannot believe we didn't see this issue! Thanks for reporting it. We'll make sure it is in the next release.
