### ISSUE TITLE
Page not displayed correctly

### ISSUE THREAD

**Issue by runam0K** [cdevroe/unmark#271]
I tried to update my unmark installation to the current version. The page is not displayed correctly in various browsers.

Url to the unmark installation: https://um.diglab.net
Screenshot: https://i.imgur.com/OBkXngU.png

PHP 7.4.9
MariaDB 10.3.23

Installation on a different server. with php 5.6.40 has the same problems. An older version runs there without any problems.

What can I do to fix the problem?

**Comment by runam0K** [comment]
Thanks for the hint. I downloaded the source code archive and not unmark.zip. 

As soon as you do it right, it works ... :D

**Comment by cdevroe** [comment]
@runam0K Yay!
