### ISSUE TITLE
$config['unmark_version'] update in config.php?

### ISSUE THREAD

**Issue by jschrab** [cdevroe/unmark#273]
Is there a technical reason that $config['unmark_version'] isn't updated in the latest release? I look at the main screen and ask myself "Wait, didn't I just update Unmark?"

**Comment by cdevroe** [comment]
@jschrab Looks [updated to me](https://github.com/cdevroe/unmark/blob/trunk/application/config/config.php#L14)

**Comment by jschrab** [comment]
@cdevroe It is that way in the repo but not in the release unmark.zip. The source code .zip and the .tar.gz files do have the right version number.

https://github.com/cdevroe/unmark/releases/tag/v2020.3

**Comment by cdevroe** [comment]
@jschrab I shall look into that!

**Comment by cdevroe** [comment]
@jschrab @yasuokav Just released [2020.4](https://github.com/cdevroe/unmark/releases/tag/v2020.4) to hopefully fix this issue.
