### ISSUE TITLE
add link manual

### ISSUE THREAD

**Issue by tristan-k** [cdevroe/unmark#28]
Please add a mask to add links manually via the main unmark site This can be helpful when you are on a public computer.

**Comment by cdevroe** [comment]
Just an update... over a year later, this is still something we plan on adding to Unmark.

**Comment by bryce-admin** [comment]
Any word (especially with HTTPS-only sites that the bookmarklet ignores)?

**Comment by nitinthewiz** [comment]
@bryce-admin The problem with HTTPS sites is that your browser (mostly Chrome) notices that an insecure (HTTP) script is being loaded on top of a secure (HTTPS) site. This throws an error which you can observe in the browser console. I use Fever RSS and HTTPS based blogs show the following error when I try to use my subscribe bookmarklet - 

Mixed Content: The page at 'https://www.instagram.com/' was loaded over HTTPS, but requested an insecure script 'http://fever.mysite.com/?feedlet'. This request has been blocked; the content must be served over HTTPS.

@cdevroe would this situation be assuaged if we use an SSL cert with our Unmark setup? 

@bryce-admin if Colin says yes, you can now grab free SSL certs from letsencrypt.org and they have awesome tutorials about how to set the cert up on your web server. This should solve your problem with the bookmarklet not working with HTTPS-only sites.

**Comment by cdevroe** [comment]
@nitinthewiz Yes, if you see most every link with Unmark.it works via HTTPS. Make sure your bookmarklet also called HTTPS.
