### ISSUE TITLE
Make Unmark available on Docker Hub

### ISSUE THREAD

**Issue by abdulocracy** [cdevroe/unmark#281]
It's great that there's an official Docker image available, but have the devs considered publishing on Docker Hub? It would make maintenance much easier for people that decide to deploy the contianer.

**Comment by ElGranLoky** [comment]
I have created a simple container, you can use it if you still need

https://hub.docker.com/r/elgranloky/unmark

**Comment by cdevroe** [comment]
Awesome @ElGranLoky
