### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by occirol** [cdevroe/unmark#286]
Hello !

I'm interested in unmark, but before going further, is this project still actively maintained ? No activities since 2 years on the code base, no activitiy on twitter, unexistant e-mail when contacting support (<unmark@cdevroe.com>]: user does not exist)...

Regards,
Fabien

**Comment by cdevroe** [comment]
Hello Fabien! I can totally understand your reticence. Unmark is still being hosted by me on [its main domain](https://unmark.it) and is actively used. The codebase is a bit long in the tooth but works great. Any issues you see here on Github are mostly related to people trying to use Unmark in an environment other than the one provided. I'm just about the only person that spends any time on it.

I've been thinking about retiring this codebase on CodeIgniter and switching the UI to be a React app on a much more simple PHP or JavaScript based API. This codebase was a bit over engineered at the time and that makes it very unwieldy to work with. I believe it could be a much more simple set up.

Overall though, I do not see myself pouring any more time into this current codebase except to fix a bug that is found which there really hasn't been in a very long time.

**Comment by BrookeDot** [comment]
I'll just chime in to say I've been using the self-hosted version of Unmarked for a few years now when I was looking for a bookmark manager. Overall I find that it works really well and am appreciative that it is open source. There have been times that I've wished it to be more feature rich but figured it was only being maintained by a single author in their "free" time. So thanks for everything getting it to this point. 

Personally, I would love to see the app remaining purely PHP/MySQL and not going down the React route unless it can be released without requiring a Node.js server which IMO does make setup slightly more complex (yes I know Docker makes this easier). Although Switching away from CodeIgniter may not be a bad idea ;) 

Anyway, thanks again for the project!

**Comment by cdevroe** [comment]
@BrookeDot Totally noted. I probably shouldn't have pointed to any specific language or framework since I haven't made any decisions. But I do know, if I want to add any features to Unmark I'll need to fork the codebase and start over I think.

That being said... I'd love to hear your ideas for features you'd like to see. :)

**Comment by occirol** [comment]
@cdevroe Thank you !
Unmark should stay simple with not too many features, I think. The one that could be very interesting is to parse the readable content of the webpage and archive it, so that if the webpage is unavailable, you can still read it or get back to it if needed.

I close the ticket and maybe you can start a discussion thread about the unmark features users are expecting.
