### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by cdevroe** [cdevroe/unmark#38]
We've recently pushed an update to Unmark that allows for internationalization (i8n). So if you're running anything newer than 1.4.0 you can begin translating Unmark into your language.

We've [written up some basic instructions on how to do this](https://github.com/plainmade/unmark/wiki/Internationalization) and we'd love some help translating Unmark into the following languages:
- [x] English
- [x] Polish
- [ ] Spanish
- [ ] German
- [ ] Dutch
- [x] Simplified Chinese
- [ ] Japanese
- [ ] Swedish
- [ ] Your language

If your language isn't listed please feel free to add it and get started.

**Comment by Menti** [comment]
Hi, I have almost translated Unmark into Spanish. I'm using shared hosting, and the translation is not showing up there. This is my language.php: 

```php
<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

// Language to use
$config['default_language'] = 'english';

// Supported languages
$config['supported_languages'] = array(
    'english' => 'en_US',
    'spanish' => 'es_ES',
    'polish' => 'pl_PL',
    'simple_chinese' => 'zh_CN',
);
```

If I change the default language to Spanish, Unmark switches to the translated version, which works perfectly. 

So I guess there's some kind of bug, or cache, or something that I can't probably control being in shared hosting (however, I have other apps with gettext translations in the same server, even one translated by myself, and they work). Or am I missing something else?

So, is it okay if I send you a pull request for this translation (with the default language set to English)? Are my files correct and the problem in my server, so you can merge?

Thanks!

**Comment by Menti** [comment]
Hi. I'd like to share my translation to Spanish, but I still have the problems that I outlined before. Should I send a pull request with my language files so you can test, or is there some other better way?

**Comment by cdevroe** [comment]
@Menti Honestly, I'm rethinking the usage of gettext. Many, many people's first experience with Unmark is marred with PHP errors because they need this extension configured or compiled or included in some way that they do not have by default. It has caused a lot of issues.

We may look into a much more simple alternative.

If anyone has ideas please put them forth.

**Comment by cdevroe** [comment]
In 1.7.2 we're going to go the more traditional approach of using a standard PHP array rather than what Unmark uses now. It not be as nice but it will certainly have broader acceptance. As such we'll need to convert these files.

I'll give it the first run but I may need help.

(BTW, if anyone would like to join our Slack channel please send me a tweet @cdevroe )
