### ISSUE TITLE
Feature Request: Autocomplete for tags

### ISSUE THREAD

**Issue by simonschaufi** [cdevroe/unmark#55]
While adding a new bookmark it would be very helpful to see and use already used tags. As a suggestion for ui component i wish to see something like that:

http://www.uicorner.com/multiple-selection-combobox-for-bootstrap-themes/

**Comment by Hans-Maulwurf** [comment]
this would be an awesome feature

**Comment by cdevroe** [comment]
@simonschaufi @ckrack @Hans-Maulwurf This is now implemented in both the main list UI and also in the bookmarklet in the proposed Version 2.0 PR. If you'd like to give them a try and provide feedback before the changes are rolled in.
